# -*- coding: utf-8 -*-
"""Board

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qbZ04-QV9DnlZoa60KDyHEH6nUjCibGe
"""

board = []

def print_board():
  pass

def check_mark():
  pass

def place_mark():
  pass

def check_win():
  pass

def main():
  print('hello')

main()